spring:
  profiles:
    active: production
  devtools:
    livereload:
      enabled: false
    restart:
      quiet-period: 900

  jpa:
    properties:
      hibernate:
        integrator_provider: org.pizzeria.api.configs.hibernate.ClassImportIntegratorIntegratorProvider
        jdbc:
          time_zone: UTC
        show_sql: true
        format_sql: true

      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED

    open-in-view: false
    hibernate:
      ddl-auto: update

  config:
    import: optional:file:local.env[.properties]

db:
  url: jdbc:mariadb://localhost:3306/pizzeria
  username: root
  password: root

logging:
  level:
    org.hibernate: info
    org.hibernate.sql: info
    org.springframework.security: debug
    org.springframework.web: info
    root: info


#    trace enabled – trace, debug, info, warn and error produce log output.
#    debug enabled – debug, info, warn and error produce log output.
#    info enabled – info, warn and error produce log output.
#    warn enabled – warn and error produce log output.
#    error enabled – Only error produces log output.