spring:
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
  devtools:
    livereload:
      enabled: false
    restart:
      quiet-period: 900

  jpa:
    properties:
      hibernate:
        integrator_provider: org.pizzeria.api.configs.hibernate.ClassImportIntegratorIntegratorProvider
        jdbc:
          time_zone: UTC
        show_sql: true
        format_sql: true

      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED

    open-in-view: false
    hibernate:
      ddl-auto: update

  config:
    import: optional:file:local.env[.properties]

logging:
  level:
    org.springframework.security: trace
    org.hibernate: info
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace