INSERT INTO pizzeria.address (id, details, `number`, street)
VALUES (1, NULL, 15, 'Avenida Alustre'),
       (2, NULL, 221, 'Calle Viciosa'),

INSERT INTO pizzeria.store (id, image, name, phone_number, schedule, address_id)
VALUES (1, 'https://i.imgur.com/AlrpKpH.png', 'Alustre', 666555666, '{"es": "Lunes a Domingo - 12PM a 12AM", "en": "Monday to Sunday - 12PM to 12AM"}', 1), (2, 'https://i.imgur.com/I3Rq9sb.png', 'Viciosa', 555666555, '{"es": "Lunes a Domingo - 12PM a 12AM", "en": "Monday to Sunday - 12PM to 12AM"}', 2);

INSERT INTO pizzeria.offer (id, caveat, description, image, name)
VALUES (1, '{"es": "Cualquiera especialidad o hasta 4 ingredientes", "en": "Any specialty or up to 4 ingredients"}',
        '{"es":"Válida todos los días en Pizzas Medianas y Familiares", "en":"Valid every day for Medium and Familiar sized Pizzas"}',
        'https://i.imgur.com/bfQpnP2.jpg', '{"es": "3x2 en Pizzas", "en":"3x2 for Pizzas"}'),
       (2, '{"es": "Cualquiera especialidad o hasta 4 ingredientes", "en": "Any specialty or up to 4 ingredients"}',
        '{"es":"Válida todos los días en Pizzas Medianas y Familiares", "en":"Valid every day for Medium and Familiar sized Pizzas"}',
        'https://i.imgur.com/bfQpnP2.jpg', '{"es": "2ª Pizza al 50%", "en":"Second Pizza at half the price"}');

INSERT INTO pizzeria.product (id, code, description, formats, image, name, prices, product_type)
VALUES (1, 'P1C',
        '{ "es": "Salsa de Tomate, Mozzarella 100%, Parmesano, Emmental, Queso Azul", "en": "Tomato sauce, 100% Mozzarella, Parmesan Cheese, Emmental Cheese, Blue Cheese"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Cuatro Quesos", "en": "Cuatro Quesos"}', '{"m": 13.3, "l": 18.3}',
        'pizza'),
       (2, 'P2C',
        '{"es": "Salsa de Tomate, Mozzarella 100%, Calabacín, Tomate Natural, Parmesano", "en": "Tomato sauce, 100% Mozzarella, Zucchini, Sliced Tomato, Parmesan cheese"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Natura", "en": "Natura"}', '{"m": 13.3, "l": 18.3}', 'pizza'),
       (3, 'P3C',
        '{"es":"Salsa de Tomate, Mozzarella 100%, Cebolla, Bacon, Queso de Cabra", "en":"Tomato sauce, 100% Mozzarella, Onions, Smoked Bacon, Goat Cheese"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Cabra Loca", "en": "Cabra Loca"}', '{"m": 13.3, "l": 18.3}',
        'pizza'),
       (4, 'P4C',
        '{"es":"Salsa de Tomate, Doble de Mozzarella 100%, Doble de Peperoni", "en":"Tomato sauce, Double 100% Mozzarella, Double Pepperoni"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Roni Pepperoni", "en": "Roni Pepperoni"}', '{"m": 13.3, "l": 18.3}',
        'pizza'),
       (5, 'P5G',
        '{"es": "Salsa de Nata, Mozzarella 100%, Cebolla, Champiñon Fresco, Doble de Bacon", "en": "Cream sauce, 100% Mozzarella, Onion, Mushrooms, Double Smoked Bacon"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Carbonara", "en": "Carbonara"}', '{"m": 14.75, "l": 20.25}',
        'pizza'),
       (6, 'P6G',
        '{"es": "Salsa de Tomate, Mozzarella 100%, Calabacín, Champiñon Fresco, Pollo, Aceite de Trufa", "en": "Tomato sauce, 100% Mozzarella, Zucchini, Mushrooms, Chicken, White Truffle Oil"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Trufa Gourmet", "en": "Trufa Gourmet"}', '{"m": 14.75, "l": 20.25}',
        'pizza'),
       (7, 'P7G',
        '{"es": "Salsa de Tomate, Mozzarella 100%, Berenjena, Calabacín, Tomate Natural, Aceitunas Negras", "en": "Tomato sauce, 100% Mozzarella, Eggplant, Zucchini, Sliced Tomato, Black Olives"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Mediterránea", "en": "Mediterránea"}', '{"m": 14.75, "l": 20.25}',
        'pizza'),
       (8, 'P8G',
        '{"es": "Salsa de Tomate, Mozzarella 100%, Jamón York, Bacon, Pepperoni, Ternera", "en": "Tomato sauce, 100% Mozzarella, York Ham, Smoked Bacon, Pepperoni, Beef"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Caníbal", "en": "Caníbal"}', '{"m": 14.75, "l": 20.25}', 'pizza'),
       (9, 'B1N', NULL, '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/1BzVHZT.png', '{"es": "Coca-Cola Clásica", "en": "Coca-Cola Classic"}',
        '{"s": 1.95, "m": 2.95}', 'beverage'),
       (10, 'B2N', NULL, '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/Nfvl5TU.png', '{"es": "Coca-Cola Zero", "en": "Coca-Cola Zero"}', '{"s": 1.95, "m": 2.95}',
        'beverage');
INSERT INTO pizzeria.product (id, code, description, formats, image, name, prices, product_type)
VALUES (11, 'B3N', NULL, '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/cmW3aYq.png', '{"es": "Fanta Naranja", "en": "Fanta Orange"}', '{"s": 1.95, "m": 2.95}',
        'beverage'),
       (12, 'B4N', NULL, '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/obYpRq6.jpg', '{"es": "Nestea Limón", "en": "Nestea Lime"}', '{"s": 1.95, "m": 2.95}',
        'beverage'),
       (13, 'B5N', NULL, '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/uCmMiKI.jpg', '{"es": "Sprite", "en": "Sprite"}', '{"s": 1.95, "m": 2.95}', 'beverage'),
       (14, 'B6N', NULL, '{"s": {"es":"330ML", "en":"330ML"}}', 'https://i.imgur.com/ejlEnRd.jpg',
        '{"es": "Aquarius Limón", "en": "Aquarius Lime"}', '{"s": 1.95}', 'beverage'),
       (15, 'B1A', NULL, '{"s": {"es":"330ML", "en":"330ML"}}', 'https://i.imgur.com/vCIvzF8.jpg',
        '{"es": "Mahou Clásica", "en": "Mahou Classic"}', '{"s": 1.95}', 'beverage'),
       (16, 'B7N', NULL, '{"s": {"es":"330ML", "en":"330ML"}}', 'https://i.imgur.com/C6ZW6h8.png',
        '{"es": "Mahou Sin", "en": "Mahou Without Alcohol"}', '{"s": 1.95}', 'beverage');