INSERT INTO pizzeria.product (description, format, image, name, price, product_type, id)
VALUES ('{ "es": "Salsa de Tomate, Mozzarella 100%, Parmesano, Emmental, Queso Azul", "en": "Tomato sauce, 100% Mozzarella, Parmesan Cheese, Emmental Cheese, Blue Cheese"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Familiar"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Cuatro Quesos", "en": "Cuatro Quesos"}',
        '{"m": 13.3, "l": 18.3}',
        'pizza',
        1),
       ('{"es": "Salsa de Tomate, Mozzarella 100%, Calabacín, Tomate Natural, Parmesano", "en": "Tomato sauce, 100% Mozzarella, Zucchini, Sliced Tomato, Parmesan cheese"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Familiar"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Natura", "en": "Natura"}',
        '{"m": 13.3, "l": 18.3}',
        'pizza',
        2),
       ('{"es":"Salsa de Tomate, Mozzarella 100%, Cebolla, Bacon, Queso de Cabra", "en":"Tomato sauce, 100% Mozzarella, Onions, Smoked Bacon, Goat Cheese"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Familiar"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Cabra Loca", "en": "Cabra Loca"}',
        '{"m": 13.3, "l": 18.3}',
        'pizza',
        3),
       ('{"es":"Salsa de Tomate, Doble de Mozzarella 100%, Doble de Peperoni", "en":"Tomato sauce, Double 100% Mozzarella, Double Pepperoni"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Familiar"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Roni Pepperoni", "en": "Roni Pepperoni"}',
        '{"m": 13.3, "l": 18.3}',
        'pizza',
        4);

INSERT INTO pizzeria.product (description, format, image, name, price, product_type, id)
VALUES ('{"es": "Salsa de Nata, Mozzarella 100%, Cebolla, Champiñon Fresco, Doble de Bacon", "en": "Cream sauce, 100% Mozzarella, Onion, Mushrooms, Double Smoked Bacon"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Familiar"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Carbonara", "en": "Carbonara"}',
        '{"m": 14.75, "l": 20.25}',
        'pizza',
        5),
       ('{"es": "Salsa de Tomate, Mozzarella 100%, Calabacín, Champiñon Fresco, Pollo, Aceite de Trufa", "en": "Tomato sauce, 100% Mozzarella, Zucchini, Mushrooms, Chicken, White Truffle Oil"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Familiar"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Trufa Gourmet", "en": "Trufa Gourmet"}',
        '{"m": 14.75, "l": 20.25}',
        'pizza',
        6),
       ('{"es": "Salsa de Tomate, Mozzarella 100%, Berenjena, Calabacín, Tomate Natural, Aceitunas Negras", "en": "Tomato sauce, 100% Mozzarella, Eggplant, Zucchini, Sliced Tomato, Black Olives"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Familiar"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Mediterránea", "en": "Mediterránea"}',
        '{"m": 14.75, "l": 20.25}',
        'pizza',
        7),
       ('{"es": "Salsa de Tomate, Mozzarella 100%, Jamón York, Bacon, Pepperoni, Ternera", "en": "Tomato sauce, 100% Mozzarella, York Ham, Smoked Bacon, Pepperoni, Beef"}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Familiar"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Caníbal", "en": "Caníbal"}',
        '{"m": 14.75, "l": 20.25}',
        'pizza',
        8);

INSERT INTO pizzeria.product (description, format, image, name, price, product_type, id)
VALUES (NULL,
        '{"s": {"es":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/1BzVHZT.png',
        '{"es": "Coca-Cola Clásica", "en": "Coca-Cola Classic"}',
        '{"s": 1.95, "m": 2.95}',
        'beverage',
        9),
       (NULL,
        '{"s": {"es":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/Nfvl5TU.png',
        '{"es": "Coca-Cola Zero", "en": "Coca-Cola Zero"}',
        '{"s": 1.95, "m": 2.95}',
        'beverage',
        10),
       (NULL,
        '{"s": {"es":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/cmW3aYq.png',
        '{"es": "Fanta Naranja", "en": "Fanta Orange"}',
        '{"s": 1.95, "m": 2.95}',
        'beverage',
        11),
       (NULL,
        '{"s": {"es":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/obYpRq6.jpg',
        '{"es": "Nestea Limón", "en": "Nestea Lime"}',
        '{"s": 1.95, "m": 2.95}',
        'beverage',
        12),
       (NULL,
        '{"s": {"es":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/uCmMiKI.jpg',
        '{"es": "Sprite", "en": "Sprite"}',
        '{"s": 1.95, "m": 2.95}',
        'beverage',
        13);

INSERT INTO pizzeria.product (description, format, image, name, price, product_type, id)
VALUES (NULL,
        '{"s": {"es":"330ML"}}',
        'https://i.imgur.com/ejlEnRd.jpg',
        '{"es": "Aquarius Limón", "en": "Aquarius Lime"}',
        '{"s": 1.95}',
        'beverage',
        14),
       (NULL,
        '{"s": {"es":"330ML"}}',
        'https://i.imgur.com/vCIvzF8.jpg',
        '{"es": "Mahou Clásica", "en": "Mahou Classic"}',
        '{"s": 1.95}',
        'beverage',
        15),
       (NULL,
        '{"s": {"es":"330ML"}}',
        'https://i.imgur.com/C6ZW6h8.png',
        '{"es": "Mahou Sin", "en": "Mahou Without Alcohol"}',
        '{"s": 1.95}',
        'beverage',
        16);